apiVersion: v1
kind: Service
metadata:
  name: graph-service
  namespace: km-system
spec:
  selector:
    app: graph-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP