{{/* templates/pdb.yaml */}}
{{- $root := . -}}
{{- range $service := .Values.services }}
{{- if and $service.enabled $service.podDisruptionBudget.enabled }}
{{- $serviceName := $service.name }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $serviceName }}-pdb
  namespace: {{ include "km.namespace" $root }}
spec:
  minAvailable: {{ $service.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
{{- end }}
{{- end }}